### ISSUE TITLE
Server returned 5XX Server Error reply

### ISSUE THREAD

**Issue by ne0lith** [loo-kuhs/tiktok-live-downloader#11]
```
❗ Ctrl+C to stop downloading and exit

[in#0 @ 000001f0ad804b40] Error opening input: Server returned 5XX Server Error reply
Error opening input file https://pull-hls-f16-tt01.tiktokcdn-us.com/stage/stream-3574707178794386352_or4/index.m3u8?expire=1728890302&sign=0c0e4e5491989e4d139902eedb0b37a1.
Error opening input files: Server returned 5XX Server Error reply
```

I'm assuming this is related to our requests not being authed?

**Comment by loo-kuhs** [comment]
Hello, it is not an authentication problem, what I see is that it responds to the request with the live stream link. The problem is that the ffmpeg error sometimes happens, try again until ffmpeg takes the link of the live stream.

**Comment by ne0lith** [comment]
```
PS A:\tiktok-live-downloader-master> node build/app.js shespicy --output downloads --format mkv

✅ Searching user's live stream: shespicy
💾 Output directory: downloads
📹 Format video: mkv

✅ 235845 bytes fetched from https://www.tiktok.com/@shespicy/live

✅ Found room id: 7420688932964272939! 🎉

✅ Found the live stream of: KNBBaby! 🎉

✅ Downloading livestream Come say hi to ./downloads/shespicy-101202415448.mkv

❗ Ctrl+C to stop downloading and exit

[in#0 @ 0000016e44564b40] Error opening input: Server returned 5XX Server Error reply
Error opening input file https://pull-hls-f16-tt01.tiktokcdn-us.com/stage/stream-3574712805537088432_or4/index.m3u8?expire=1728975287&sign=86096bb456e09c8d8b13419451838a91.
Error opening input files: Server returned 5XX Server Error reply

PS A:\tiktok-live-downloader-master> node build/app.js shespicy --output downloads --format mkv

✅ Searching user's live stream: shespicy
💾 Output directory: downloads
📹 Format video: mkv

✅ 237723 bytes fetched from https://www.tiktok.com/@shespicy/live

✅ Found room id: 7420688932964272939! 🎉

✅ Found the live stream of: KNBBaby! 🎉

✅ Downloading livestream Come say hi to ./downloads/shespicy-101202415502.mkv

❗ Ctrl+C to stop downloading and exit

[in#0 @ 000002582cdc4b40] Error opening input: Server returned 5XX Server Error reply
Error opening input file https://pull-hls-f16-tt01.tiktokcdn-us.com/stage/stream-3574712805537088432_or4/index.m3u8?expire=1728975301&sign=8917e36ced4a89b46afeea41ee1a2d79.
Error opening input files: Server returned 5XX Server Error reply

PS A:\tiktok-live-downloader-master> node build/app.js shespicy --output downloads --format mkv

✅ Searching user's live stream: shespicy
💾 Output directory: downloads
📹 Format video: mkv

✅ 236131 bytes fetched from https://www.tiktok.com/@shespicy/live

✅ Found room id: 7420688932964272939! 🎉

✅ Found the live stream of: KNBBaby! 🎉

✅ Downloading livestream Come say hi to ./downloads/shespicy-101202415511.mkv

❗ Ctrl+C to stop downloading and exit

[in#0 @ 0000021eac7c4b40] Error opening input: Server returned 5XX Server Error reply
Error opening input file https://pull-hls-f16-tt01.tiktokcdn-us.com/stage/stream-3574712805537088432_or4/index.m3u8?expire=1728975311&sign=1932c08f714d81ec4b1bd769c0d06db5.
Error opening input files: Server returned 5XX Server Error reply

PS A:\tiktok-live-downloader-master> node build/app.js shespicy --output downloads --format mkv

✅ Searching user's live stream: shespicy
💾 Output directory: downloads
📹 Format video: mkv

✅ 216739 bytes fetched from https://www.tiktok.com/@shespicy/live
Error: ❌ No room id found!
    at matchRoomId (A:\tiktok-live-downloader-master\build\helpers\matchRoomId.js:12:15)
    at A:\tiktok-live-downloader-master\build\helpers\downloadLiveStream.js:29:50
    at Generator.next (<anonymous>)
    at fulfilled (A:\tiktok-live-downloader-master\build\helpers\downloadLiveStream.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This feels a little more like something is wrong, and not just a random ffmpeg error?

**Comment by loo-kuhs** [comment]
`~ rukaz  ﲵ pwsh                                                                                 0ms  Oct 1 at 01:07:35
~  home ~ ttl shespicy
We are not in the project directory. Changing the directory
Running the node application

🔎 Searching shespicy's live stream
💾 Output directory: downloads
📹 Format video: mp4

✅ 238537 bytes fetched from https://www.tiktok.com/@shespicy/live

✅ Found room id: 7420688932964272939! 🎉

✅ [1] Found KNBBaby live stream url! 🎉

✅ Downloading livestream Come say hi to ./downloads/shespicy-110202410802.mp4

❗ Ctrl+C to stop downloading and exit

frame= 1049 fps= 29 q=-1.0 size=   16896KiB time=00:00:42.00 bitrate=3295.5kbits/s speed=1.16x
~ rukaz   master ﲵ pwsh                                                     43s 383ms  Oct 1 at 01:08:43   20.15.1
~  tiktok-live-ts ~ node .\build\app.js shespicy -f 'mkv'

🔎 Searching shespicy's live stream
💾 Output directory: downloads
📹 Format video: mkv

✅ 239245 bytes fetched from https://www.tiktok.com/@shespicy/live

✅ Found room id: 7420688932964272939! 🎉

✅ [1] Found KNBBaby live stream url! 🎉

✅ Downloading livestream Come say hi to ./downloads/shespicy-110202410900.mkv

❗ Ctrl+C to stop downloading and exit

x265 [info]: HEVC encoder version 4.0+6-a069836f3
x265 [info]: build info [Windows][GCC 14.2.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 12 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 3 / wpp(30 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 25 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-23.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip mode=1 signhide tmvp
x265 [info]: tools: b-intra strong-intra-smoothing lslices=8 deblock sao
frame=  147 fps= 24 q=28.2 size=    2048KiB time=00:00:05.80 bitrate=2892.6kbits/s speed=0.937x
~ rukaz   master ﲵ pwsh                                                      8s 965ms  Oct 1 at 01:09:08   20.15.1
~  tiktok-live-ts ~`

----
Idk man, that looks like a bug or something. What version of ffmpeg do you have installed?
