### ISSUE TITLE
Error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by ethanzito** [loo-kuhs/tiktok-live-downloader#15]
hi. I used this nice project two months ago. Today i had some errors so i updated it. It got ride of 'em but now i have a cookie issue. The session folder and file date shows as new so i guess last time they weren't needed.  I looked inside the file and seems fine, has a total of 199 lines. Tried deleting the file to re-create it and still the same output.

```typescript
[User@User tiktok-live-downloader]$ node build/app.js streamer --output mydownloads --format mp4

🔎 Searching streamer's live stream
💾 Output directory: mydownloads
📹 Format video: mp4

✅ 240321 bytes fetched from https://www.tiktok.com/@streamer/live

✅ Found room id: 1234567889870787801! 🎉

🍪 Cookie file not found. Creating new cookie.

🍪 Creating cookie for API authentication...

🚀 Launching puppeteer to retrieve session cookie...

✅ Cookie successfully created for API usage.

📝 Saving cookie to '/*/tiktok-live-downloader/session/cookie.txt'

✅ Cookie successfully saved to file: /*/tiktok-live-downloader/session/cookie.txt

🍪 Cookie loaded. Evaluating cookie...

🍪 Cookie string created.
❌ Error: SyntaxError: Unexpected end of JSON input

[User@User tiktok-live-downloader]$ npm -v
10.9.2
[User@User tiktok-live-downloader]$ node -v
v23.5.0
```

**Comment by loo-kuhs** [comment]
Hi, thank you for reporting the error, checking

**Comment by loo-kuhs** [comment]
I found the problem, TikTok was rejecting the request to its API because the User-Agent was missing in the header. Try downloading the new version.

**Comment by ethanzito** [comment]
thanks. it solved it. i'm having another issue now. module shows as updated. i don't know if i should make a new topic
```typescript
[User@User tiktok-live-downloader]$ node build/app.js Removed --output mydownloads --format mp4 -d

🔎 Searching Removed's live stream
💾 Output directory: mydownloads
📹 Format video: mp4

✅ 240974 bytes fetched from https://www.tiktok.com/@Removed/live

✅ Found room id: 1234567889870787801! 🎉

🍪 Cookie loaded. Evaluating cookie...

🍪 Cookie string created.
Error: ❌ Error: TypeError: Cannot read properties of undefined (reading 'flv_pull_url')
    at /*/tiktok-live-downloader/build/helpers/downloadLiveStream.js:52:19
    at Generator.throw (<anonymous>)
    at rejected (/*/tiktok-live-downloader/build/helpers/downloadLiveStream.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

```

**Comment by ethanzito** [comment]
thank you. it works now

**Comment by loo-kuhs** [comment]
Yeah sometime u need retry, or sometimes you get this error because the user has an age restriction, you can validate with the url: [https://webcast.tiktok.com/webcast/room/info/?aid=1988&room_id=](https://webcast.tiktok.com/webcast/room/info/?aid=1988&room_id=[[room id]]) 

if you get something like this, then the user has age restriction activated

` "age_restricted": {
      "AgeInterval": 4,
      "restricted": false,
      "source": 1
    },`

the next example is when the user has not age restrictions:
`"age_restricted": {
      "AgeInterval": 0,
      "restricted": false,
      "source": 0
    },`

**Comment by ethanzito** [comment]
I'm adding context for the comment above because i deleted mine after solving it a minute after.
```typescript
❌ Error: TypeError: Cannot read properties of undefined (reading 'flv_pull_url')
``` 
I recommend if reporting an issue not only try with the same user like i did haha. In my case i did it with someone who showed as online and maybe they went off the moment i tried. 
I'll have the age restriction tip in mind for next time.
