### ISSUE TITLE
Error: No live stream found

### ISSUE THREAD

**Issue by orhogi** [loo-kuhs/tiktok-live-downloader#4]
![Desktop Screenshot 2024 07 17 - 17 21 19 80](https://github.com/user-attachments/assets/44f57771-7780-41fe-bfe1-509206521447)

I keep getting this error even tho that person is live and I tried with a few streams all of them give me this error

**Comment by loo-kuhs** [comment]
Hi, sorry and thank you very much for the warning.

With the new update it should work now.

**Comment by orhogi** [comment]
OMG, thank you! You're a lifesaver
