### ISSUE TITLE
file format not supported ?

### ISSUE THREAD

**Issue by orhogi** [loo-kuhs/tiktok-live-downloader#5]
![image](https://github.com/user-attachments/assets/4c4a423c-3e80-4f15-9e54-a3882a1d1cb3)

**Comment by loo-kuhs** [comment]
Hello. I am not sure what generates that error. Did you try opening the video with another video player?

**Comment by orhogi** [comment]
Yes I tried VLC player still didn't help and I also tried to convert the file into a different format which it didn't work either

**Comment by loo-kuhs** [comment]
Hi, did you stop the download before opening the file?

I have tried by myself with that same tiktok user and I was able to play the video.

![image](https://github.com/user-attachments/assets/d3a9d1d1-993e-4405-b427-a856a8d51e33)

And as a tip, after starting the tiktok live download, wait two or three minutes before stopping the download.

**Comment by orhogi** [comment]
Hey and yes I stop the download Before opening the file and I just tried to leave it for 4 minutes and still the same problem

**Comment by loo-kuhs** [comment]
I don't know man, I tried to replicate the error. I need more information on how you are using the tool.

**Comment by loo-kuhs** [comment]
I think I know what is happening, you are trying to open the video file when the tool is active.

1st.- I assume you start the download tool.
![image](https://github.com/user-attachments/assets/21587ad4-0d9a-4384-b991-51a4619178da)

2nd.- Then I think you try to open the video file.
![image](https://github.com/user-attachments/assets/2345370f-edd0-4a98-9cf2-0661a6647945)

3rd.- You're getting the error.
![image](https://github.com/user-attachments/assets/a6fcf26f-e786-4b9f-9f41-b2f3afd76d7d)


------

**Before opening the file, you must stop the download process. The file will not work until you do this.**

**In the command console just press CTRL + C on the keyboard.**

Then you can open the file.
![image](https://github.com/user-attachments/assets/9d425010-d1d7-462e-8a75-1f3bab6f77a6)

**Comment by orhogi** [comment]
![image](https://github.com/user-attachments/assets/835774b7-5124-4646-996c-f8d671350848)
 I close the tool  but that's enough tho thank you for trying to help

**Comment by loo-kuhs** [comment]
You can try using it with pwsh, you can download it from the microsoft store
![image](https://github.com/user-attachments/assets/5bbd10fa-b2a5-4cc3-bac2-af4e0b8f7f43)

**Comment by orhogi** [comment]
ill try that

**Comment by loo-kuhs** [comment]
sure man

**Comment by orhogi** [comment]
Well that worked for some reason

**Comment by orhogi** [comment]
Ty again for this amazing project and for your help I really appreciate it

**Comment by loo-kuhs** [comment]
Thanks man, great to know.
