### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by forceware680** [loo-kuhs/tiktok-live-downloader#8]
![image](https://github.com/user-attachments/assets/f94f5da1-6238-4fbb-aabd-e6a39bf49dfb)

**Comment by loo-kuhs** [comment]
Hello, thank you for notifying me of this error.

I need more information:

Are you using the most recent version of the project?
Did you build the project with npm run build?
What version of nodejs and npm are you using?

Finally, can you try using powershell from the Microsoft Store?

**Comment by forceware680** [comment]
Are you using the most recent version of the project?
-- yes
Did you build the project with npm run build?
-- absolutely yes
What version of nodejs and npm are you using?
-- node js version 16.17.1
-- npm version 9.2.0

hmm looks like problem is restricted by country or somethings.. when use this tool live stream is not available even streamer is live.

**Comment by forceware680** [comment]
solved by upgrade node js version

**Comment by loo-kuhs** [comment]
Yes, this project uses native fetch, so you need node.js 18.0 or superior.
